### ISSUE TITLE
Settings won't open for file:/// pages

### ISSUE THREAD

**Issue by seanlinsley** [hackademix/noscript#228] opened 2022-02-18 22:57 UTC
Currently, it's impossible to change settings for locally hosted files because the settings pane won't open. Right clicking will open a separate settings window, but it immediately closes itself.

With so many changes to NoScript in the last few days it's hard to tell where it broke. It had been a few days since I'd last restarted Firefox.

Maybe these errors in the browser console can help? The promise-related errors seem to have been triggered by me trying to open the settings pane.

<img width="973" alt="Screen Shot 2022-02-18 at 4 33 45 PM" src="https://user-images.githubusercontent.com/688886/154772025-7733163b-19de-4a35-9c1c-8303a62ae005.png">

**Comment by hackademix** [comment] 2022-02-18 23:01
Duplicate of #227

**Closed as completed by hackademix** 2022-02-18 23:01 UTC
