### ISSUE TITLE
unrestricted CSS being disabled on sites which can run scripts cause troubles in some sites.

### ISSUE THREAD

**Issue by Alchete** [hackademix/noscript#204] opened 2021-07-05 15:17 UTC
As of 11.2.9 and Chrome v91 a number of websites no longer function despite manually enabling all JS classes for the site.

Examples:
https://twitter.com/
https://seekingalpha.com

**Comment by hackademix** [comment] 2021-07-05 15:33
Please double check that the "unrestricted CSS" capability is checked in your TRUSTED preset (_NoScript Options>General>Preset customization_).
If it's not, could you please tell me whether it has been an automatic update or you manually installed 11.2.9, and/or if you manually unchecked that capability?
Thanks.

**Comment by Alchete** [comment] 2021-07-05 15:39
Hi hackademix, thanks for the troubleshooting advice.  That option is UNCHECKED in my plugin.  I did not change it recently.  And I've had noscript installed for a year or more now, so this was an automatic update for me.

I don't remember if I unchecked this option when first installing (long ago), but I tend to doubt that I went into the settings to specifically disable this on my own, though I can't rule that out 100%.

Checking that option fixes the problem!!  Thank you.

**Comment by fefrei** [comment] 2021-07-09 07:30
Just to add to this: I had the same problem, and the same fix worked for me.
I'm using Microsoft Edge (the Chromium one), and this seemed to happen after a browser update. I can reproduce this with `Version 91.0.864.64 (Official build) (64-bit)`.

**Comment by hackademix** [comment] 2021-07-28 06:35
This should be fixed by [11.2.11rc4](https://github.com/hackademix/noscript/releases/tag/11.2.11rc4).
Either verify this release candidate by installing the content of the zip as an unpacked extension, or wait for 11.2.11 (identical) to be approved on the Chrome/Edge stores.

**Comment by fefrei** [comment] 2021-07-28 14:38
Unfortunately, it looks like this still is an issue. I updated to `11.2.11` (from the Chrome store), restarted Microsoft Edge, and reverted the `unrestricted CSS` permission.

Here's a render of [GitLab.com](https://gitlab.com/explore):

![image](https://user-images.githubusercontent.com/3078885/127341590-4c1b310a-cb3e-4973-836a-686470996bff.png)

For comparison, with `unrestricted CSS`:

![image](https://user-images.githubusercontent.com/3078885/127341699-87638231-27cc-4b7b-9eec-0368715a8531.png)

I'm running Microsoft Edge `92.0.902.55 (Official build) (64-bit)`.

**Comment by hackademix** [comment] 2021-07-29 20:57
OP's test cases are fixed in 11.2.11, AFAIT. 
The different issue reported in the [previous comment](#issuecomment-888364797) is being handled in issue #207. 
Closing, please feel free to file other issues as needed.

**Closed as completed by hackademix** 2021-07-29 20:57 UTC
