### ISSUE TITLE
UI not usable on Fedora 31 (Firefox on Wayland)

### ISSUE THREAD

**Issue by mabachel** [hackademix/noscript#112] opened 2019-11-06 16:52 UTC
The NoScript UI is not usable / functioning / interacting after upgrading from Fedora 30 to 31 since it defaults to Fedora on Wayland rather than X11 on GNOME Desktops (https://fedoramagazine.org/firefox-tips-for-fedora-31/).

A current workaround is to use Firefox on X11 by installing firefox-x11 package via dnf. One has to explicitly start / run Firefox on X11 since all normal Firefox links will still start Firefox on Wayland.

Firefox 70.0
NoScript 11.0.7
GNOME 3.34.1

**Comment by hackademix** [comment] 2019-11-07 16:08
Not sure what part Wayland is supposed to play in this issue, but I cannot reproduce in Ubuntu 18.04 (the distro I've got readily available) forcing Wayland on logon.
Does this happen with other extensions / parts of the Firefox UI / web pages  as well? It would be very weird if it affected just NoScript, since the UI of WebExtensions is implemented as normal HTML/CSS/JS pages.

**Comment by mabachel** [comment] 2019-11-07 16:51
Note that if I run Firefox on X11 on Fedora 31 I am still using Wayland but Fedora is using XWayland (X Clients under Wayland = XWayland). I think this is different than forcing X11 on logon. 

It does not affect other addons like uBlock, Tab Session Manger or Tree StyleTab nor any other UI function of Firefox itself (no webpages affected as well).

I use 
```
.mozilla/firefox/2vubbu8q.default/chrome/userChrome.css
#tabbrowser-tabs { visibility: collapse !important; }
```
but without that file the problem persists.

It is like the UI does not match with the control buttons. I can open the UI by clicking on the NoScript S but while hovering over the Untrusted icon it shows the question mark it would normally show while hovering over the domain name. Anything further right to the Untrusted icon has no effect (clicking does nothing and no new hover icons). It is similar for the very top buttons: I can click on close and reload but anything further right has no effect.

I also use
```
layers.acceleration.force-enabled true
gfx.webrender.enabled true
```
and I will check now if switching these back to default (false) have any effect. Nevertherless I have them on true on Firefox for X11 and everything works as expected.

I also use two monitors in extended mode.

**Comment by mabachel** [comment] 2019-11-07 16:55
> 
> ```
> layers.acceleration.force-enabled true
> gfx.webrender.enabled true
> ```
no effect switching back to default in about:config

**Comment by mabachel** [comment] 2019-12-04 07:26
The problem persists on Firefox 71

**Comment by hackademix** [comment] 2019-12-04 09:02
OK, guess it's worth setting up a VM with Fedora 31. Just stock distro Firefox with NoScript, or do I need something else to reproduce?

**Comment by mabachel** [comment] 2019-12-04 09:06
Should be all you need.
Fedora 31 Workstation (GNOME)

Thanks for the effort!
Let me know if / how I can help.

**Comment by hackademix** [comment] 2019-12-05 18:50
Unfortunately I cannot reproduce, at least not in a VM even if emulating a double screen setup (which in VBox is very painful of its own).
BTW, does your problem happen only with two screens?
On both screen or just one?
Have they got the same resolution and DPI?
![image](https://user-images.githubusercontent.com/376122/70264147-2b786600-1798-11ea-9d09-fcbccfbc4c6b.png)

**Comment by mabachel** [comment] 2019-12-11 07:49
Sorry for the delay..

Both monitors are 24" 1920x1200 displays (yes, same dpi).
It happens on both monitors.
I just turned one monitor and rebooted, but the problem persists.
![Screenshot from 2019-12-11 08-41-18](https://user-images.githubusercontent.com/41041853/70601569-9e4b6c00-1bf2-11ea-8606-4bd3e17b558e.png)
![Screenshot from 2019-12-11 08-42-34](https://user-images.githubusercontent.com/41041853/70601570-9e4b6c00-1bf2-11ea-81d7-1b01671add9b.png)

At the moment of the screenshots I am hovering over the DEFAULT button but instead of seeing the index finger icon I see the question mark icon (usually seen while hovering over the domain name).

**Comment by hackademix** [comment] 2019-12-11 23:12
Thank you for your screenshot, it's been very helpful indeed.
As you can notice, the menu origin (where the tiny arrow extrudes from the panel) is on the wrong side, and it apparently offsets all the input coordinates by a large amount.
This doesn't seem to be Wayland-specific, but Fedora (theme?) specific. In facts, I can reproduce on Fedora, with just one monitor, no matter if I select Wayland or XOrg at login time, while I cannot reproduce it on Ubuntu XOrg nor Ubuntu Wayland.
Moreover, this is not NoScript-specific at all. You can see it in NoScript and not in the other extensions you've got installed because NoScript is the only one whose icon is placed on the left side of you toolbar.
Just try to move on the left uBlock or any other one providing a popup menu, and you'll see the same issue affecting them too. The obvious work around is keeping all your extensions on the right.
I strongly suggest to file a bug report in both Mozilla's and Redhat's bug trackers.
Closing for now.

**Closed as completed** 2019-12-11 23:13 UTC

**Comment by mabachel** [comment] 2019-12-12 07:45
I filed a bug on Redhat's Bug Tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1782704

**Comment by mabachel** [comment] 2020-01-07 08:04
I just filed a bug on Mozillas Bug Tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1607404
